version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 2003
      MYSQL_DATABASE: compagnie
    ports:
      - "3307:3306"
    networks:
      - app-network

  springboot-app:
    image: springboot-app  # This should be your built image name
    container_name: springboot-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
