spring.application.name=SpringDataRestApplication

# MariaDB JDBC URL (using the internal Docker network)
spring.datasource.url=jdbc:mariadb://mariadb:3306/compagnie
spring.datasource.username=root
spring.datasource.password=2003
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.base-path=/api

# Hibernate dialect for MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
